apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-custom-vpc-nlb
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: watson-nlp-custom
  ports:
   - name: http
     protocol: TCP
     port: 8080
     targetPort: 8080